from enum import Enum


# FastAPI에서 처리하는 실제로 처리하는 ChatState
# 1. GENERATING_QUESTION
# 2. GENERATING_ADDITIONAL_QUESTION
# 3. EVALUATING_ANSWER_AND_LOGGING
# 4. PRESENTING_CONCEPT_EXPLANATION
# 5. REEXPLAINING_CONCEPT
# 6. WAITING_KEYWORD_FOR_PAGE_SEARCH
class ChatState(str, Enum):
    WAITING_USER_SELECT_FEATURE = "WAITING_USER_SELECT_FEATURE"
    WAITING_PROBLEM_CRITERIA_SELECTION = "WAITING_PROBLEM_CRITERIA_SELECTION"
    WAITING_CHAPTER_RANGE_INPUT = "WAITING_CHAPTER_RANGE_INPUT"
    WAITING_CONCEPT_KEYWORD_INPUT = "WAITING_CONCEPT_KEYWORD_INPUT"
    GENERATING_QUESTION_WITH_RAG = "GENERATING_QUESTION_WITH_RAG"
    GENERATING_ADDITIONAL_QUESTION = "GENERATING_ADDITIONAL_QUESTION"
    GENERATING_ADDITIONAL_QUESTION_WITH_RAG = "GENERATING_ADDITIONAL_QUESTION_WITH_RAG"
    EVALUATING_ANSWER_AND_LOGGING = "EVALUATING_ANSWER_AND_LOGGING"
    WAITING_NEXT_ACTION_AFTER_LEARNING = "WAITING_NEXT_ACTION_AFTER_LEARNING"
    PRESENTING_CONCEPT_EXPLANATION = "PRESENTING_CONCEPT_EXPLANATION"
    WAITING_CONCEPT_RATING = "WAITING_CONCEPT_RATING"
    WAITING_REASON_FOR_LOW_RATING = "WAITING_REASON_FOR_LOW_RATING"
    REEXPLAINING_CONCEPT = "REEXPLAINING_CONCEPT"
    WAITING_CONCEPT_INPUT = "WAITING_CONCEPT_INPUT"
    WAITING_KEYWORD_FOR_PAGE_SEARCH = "WAITING_KEYWORD_FOR_PAGE_SEARCH"
    PROCESSING_PAGE_SEARCH_RESULT = "PROCESSING_PAGE_SEARCH_RESULT"


class Sender(str, Enum):
    USER = "USER"
    AI = "AI"


class MessageType(str, Enum):
    TEXT = "TEXT"
    SELECTION = "SELECTION"
    RATING = "RATING"
    FEEDBACK = "FEEDBACK"
