spring:
  application:
    name: application

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:mysql://127.0.0.1:3306/chatbot?useSSL=false&serverTimezone=Asia/Seoul
#    username: root
#    password: 1234
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    time-zone: Asia/Seoul

  messages:
    encoding: UTF-8

  mail:
    host: smtp.gmail.com
    port: 587
#    username: ${MAIL_USERNAME}
    username: ssy06116@gmail.com
#    password: ${MAIL_PASSWORD}
    password: jnnhbpoxzcsygcps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    transport:
      protocol: smtp

  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true


# ?? ??? spring ??? ???? ?? ??? ??

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,application/json

logging:
  level:
    org.springframework.web: DEBUG
    com.example: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    defaults:
      enabled: true
    db:
      enabled: true
    mysql:
      enabled: true

app:
#  jwtSecret: ${JWT_SECRET}
  jwtSecret: QwErTyUiOpAsDfGhJkLzXcVbNmQwErTyUiOpAsDfGhJkLzXcVbNm1234567890QWERTYUIOPASDFGHJKLZXCVBNM
  jwtExpirationMs: 86400000
  jwtRefreshExpirationMs: 604800000

file:
#  upload-dir: ${UPLOAD_DIR_PATH}
  upload-dir: D:/KDT_BE12_Toy_Project4/application-server/application/src/main/resources/static/pdf